### ISSUE TITLE
redmine 5.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [eXolnet/redmine_queries_count#7]
hello mr @xel1045 
im install your plugin but  dont know how i use it or where i can configure it or enable it?
plz put describition to know how its working

**Comment by xel1045** [comment]
There was a bug that prevent it from being display in the query form. If you update the plugin to v1.4.2, you should now see a checkbox in the query creation/edition form to enable the feature:

![Screenshot 2024-02-27 at 12 03 38](https://github.com/eXolnet/redmine_queries_count/assets/1497697/ad66dbf6-fe53-41ed-8677-f110f48c33cb)
